name: Build
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Build Vue
      shell: bash
      run: |
        npm install
        npm run build
        cd blog/.vitepress/dist
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git init
        git add -A
        git commit -m 'Build'
        git push -f https://flaribbit:${{ secrets.GITHUB_TOKEN }}@github.com/flaribbit/flaribbit.github.io master:gh-pages
