name: Build
on: [push, pull_request]
jobs:
  Vitepress_build:
    runs-on: ubuntu-latest
    name: Vitepress build
    steps:
    - uses: actions/checkout@v2
    - name: Setup and build
      shell: bash
      run: |
        npm install
        npm run build
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: www
    - name: Update github page
      shell: bash
      run: |
        cd www
        rm -rf assets posts tags
        cp -rf ../.vitepress/dist/* .
        git config --global user.email "1149761294@qq.com"
        git config --global user.name "flaribbit"
        git add -A
        git commit -m autobuild
        git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git gh-pages
